### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s1-evaluacion-intermedia-natalia-pn#1]
Good job @natalia-pn! A clean and tidy exercise, the page looks nice in a web browser although we have some work to do with both the HTML and CSS code.

Here we have some tips to improve your exercise:

- [ ] Menu items would be more OK inside an unordered list
- [ ] Be careful with z-index numbers because the header should always be over the page content
- [ ] In mobile devices or small screen the header is partially hidden under the content
- [ ] Let's get rid of these default BODY margins 
- [ ] If there were justice in the world, there should be only one `H1` per page
- [ ] Class selectors are free, let's use them instead tag selectors
- [ ] Remember that `block` elements don't need to have set a width property up to 100% nor 100vw
- [ ] Use viewport units to make elements fit the browser height, instead of percentages

Once you have those fixed you can finish the little details missing

Let me know if you have any doubts ;)

**Comment by natalia-pn** [comment]
Thanks! I worked on it yesterday before you sent me the issue. I had a look at your solution to get help. :)
